<?php

/**
 * Implements hook_theme().
 */
function twelve_app_theme() {
  return [
    'today_progress' => [
      'variables' => [
        'debug' => '',
        'game_nid' => '',
        'excercises' => [],
        'completion_url' => ''
      ],
    ],
    'puzzle' => [
      'variables' => [
        'debug' => '',
        'game_nid' => '',
        'excercises' => [],
        'progress_nid' => '',
        'finished_items' => [],
      ],
    ],
  ];
}
