<?php

/**
 * Implements hook_theme().
 */
function twelve_app_theme() {
  return [
    'bursts' => [
      'variables' => [
        'debug' => '',
        'error_message' => '',
        'game_nid' => '',
        'exercises' => [],
        'completion_url' => '',
        'progress_nid' => '',
        'finished_items' => [],
      ],
    ],
    'puzzle' => [
      'variables' => [
        'debug' => '',
        'error_message' => '',
        'game_nid' => '',
        'exercises' => [],
        'progress_nid' => '',
        'finished_items' => [],
      ],
    ],
    'bingo' => [
      'variables' => [
        'debug' => '',
        'error_message' => '',
        'game_nid' => '',
        'exercises' => [],
        'progress_nid' => '',
        'finished_items' => [],
      ],
    ],
    'seven_summits' => [
      'variables' => [
        'debug' => '',
        'error_message' => '',
        'summits' => [],
      ],
    ],
  ];
}

/**
 * For development environment replace vue.min.js with vue.js
 * Implements hook_library_info_alter().
 */
function twelve_app_library_info_alter(&$libraries, $extension) {
  if (getenv('ENVIRONMENT') != 'development') {
    return;
  }

  if ($extension != 'openy_system') {
    return;
  }

  unset($libraries['vue']['js']['https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.11/vue.min.js']);
  $libraries['vue']['js']['https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.11/vue.js'] = [
    'type' => 'external'
  ];
}
