<?php

use Drupal\twelve_user\Form\UserRegisterForm;
use Drupal\twelve_user\Form\UserFamilyEdit;

/**
 * Implements hook_theme().
 */
function twelve_user_theme() {
  return [
    'user-statistics' => [
      'variables' => [
        'lifetime_bursts' => '',
        'signin_streak' => '',
        'max_signin_streak' => '',
        'art_collector' => '',
        'bingo_champion' => '',
        'uid' => ''
      ]
    ]
  ];
}

/**
 * Implements hook_entity_type_build().
 */
function twelve_user_entity_type_build(array &$entity_types) {
  // Map the Project Form view mode to the class who handle that view mode.
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  if (isset($entity_types['user'])) {
    $entity_types['user']
      ->setFormClass('register', UserRegisterForm::class)
      ->setFormClass('family_edit', UserFamilyEdit::class);
  }
}
