#!/usr/bin/env bash

## Test site installation
##
## Usage: fin test

# Abort if anything fails
set -e

CURRENT_DIR="$(dirname "$0")"
source "${CURRENT_DIR}/includes/helpers.sh"

echo "This scrips require to have dump.sql file in ${PROJECT_ROOT}"/"${DOCROOT}"

cd ${PROJECT_ROOT}/${DOCROOT}/sites/default
fin exec "drush sql-drop -y"
fin exec "\`drush sql-connect\` < ../../dump.sql"
cd ${PROJECT_ROOT}/${DOCROOT}
rm dump.sql
fin exec "drush updb"
fin exec "drush cache-rebuild"
echo-green "Done!"
